#!/bin/sh
dbus-send --system --dest=org.freedesktop.DBus --type=method_call --print-reply --reply-timeout=200 / org.freedesktop.DBus.NameHasOwner string:org.freedesktop.Policy.Power | grep -q 'boolean true'
